platform:
  - x86
  - x64

matrix:
 allow_failures:
  - platform: x86
  - platform: x64

environment:
 matrix:
 # node.js
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"
  - nodejs_version: "0.12"
# io.js
  - nodejs_version: "1.0"  

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build: off

on_success:
  ECHO "completed installation"
  
test_script:
  - cmd: dir
  - cmd: cd js
  - cmd: npm install
  - cmd: cd bin
   # Output useful info for debugging.
  - cmd: node spark.js
  - cmd: node --version
  - cmd: npm --version

deploy: OFF
